server: # REST server
  port: 2333
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "please_dont_change_this_section_if_you_are_using_the_docker_image"
    ws:
      port: 80
      host: 0.0.0.0
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      mixer: false
      http: false
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 600
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO